export const FOOD_ITEMS = [
  {
    name: 'Pad Thai',
    origin: 'Thailand',
    imgUrl: 'assets/pad_thai.png',
    ingredients: [
      'rice noodle',
      'eggs',
      'bean sprouts',
      'scallions',
      'garlic',
      'shallots',
      'tamarind paste',
      'fish sauce',
      'palm sugar',
      'lime',
      'peanuts',
      'chili flakes',
      'cilantro',
    ],
  },
  {
    name: 'Lomo Saltado',
    origin: 'Peru',
    imgUrl: 'assets/lomo_saltado.png',
    ingredients: [
      'beef',
      'rice',
      'onion',
      'tomatoes',
      'bell peppers',
      'garlic',
      'soy sauce',
      'vinegar',
      'cilantro',
      'aji amarillo paste',
    ],
  },
  {
    name: 'Aguadito',
    origin: 'Peru',
    imgUrl: 'assets/aguadito.png',
    ingredients: [
      'Chicken (whole or in pieces)',
      'Rice',
      'Cilantro',
      'Aji amarillo (yellow chili pepper)',
      'Onion',
      'Garlic',
      'Vegetables (such as peas, carrots, and corn)',
      'Vegetable or chicken broth',
      'Lime juice',
      'Salt',
      'Pepper',
    ],
  },
  {
    name: 'Aji De Gallina',
    origin: 'Peru',
    imgUrl: 'assets/aji_de_gallina.png',
    ingredients: [
      'Chicken breast',
      'Aji amarillo (yellow chili pepper)',
      'Bread slices (for thickening)',
      'Milk',
      'Vegetable oil',
      'Onion',
      'Garlic',
      'Ground walnuts or pecans',
      'Parmesan cheese',
      'Evaporated milk',
      'Salt',
      'Pepper',
      'Boiled eggs (optional, for garnish)',
      'Black olives (optional, for garnish)',
      'Rice or potatoes (served as a side)',
    ],
  },
]
