export const FOOD_ITEMS = [
  {
    name: 'Pad Thai',
    origin: 'Thailand',
    imgUrl: 'assets/pad_thai.png',
    ingredients: [
      'rice noodle',
      'eggs',
      'bean sprouts',
      'scallions',
      'garlic',
      'shallots',
      'tamarind paste',
      'fish sauce',
      'palm sugar',
      'lime',
      'peanuts',
      'chili flakes',
      'cilantro',
    ],
  },
  {
    name: 'Lomo Saltado',
    origin: 'Peru',
    imgUrl: 'assets/lomo_saltado.png',
    ingredients: [
      'beef',
      'rice',
      'onion',
      'tomatoes',
      'bell peppers',
      'garlic',
      'soy sauce',
      'vinegar',
      'cilantro',
      'aji amarillo paste',
    ],
  },
  {
    name: 'Aguadito',
    origin: 'Peru',
    imgUrl: 'assets/aguadito.png',
    ingredients: [
      'Chicken (whole or in pieces)',
      'Rice',
      'Cilantro',
      'Aji amarillo (yellow chili pepper)',
      'Onion',
      'Garlic',
      'Vegetables (such as peas, carrots, and corn)',
      'Vegetable or chicken broth',
      'Lime juice',
      'Salt',
      'Pepper',
    ],
  },
  {
    name: 'Aji De Gallina',
    origin: 'Peru',
    imgUrl: 'assets/aji_de_gallina.png',
    ingredients: [
      'Chicken breast',
      'Aji amarillo (yellow chili pepper)',
      'Bread slices (for thickening)',
      'Milk',
      'Vegetable oil',
      'Onion',
      'Garlic',
      'Ground walnuts or pecans',
      'Parmesan cheese',
      'Evaporated milk',
      'Salt',
      'Pepper',
      'Boiled eggs (optional, for garnish)',
      'Black olives (optional, for garnish)',
      'Rice or potatoes (served as a side)',
    ],
  },
  {
    name: 'Arroz Tapado',
    origin: 'Peru',
    imgUrl: 'assets/arroz_tapado.png',
    ingredients: [
      'Ground beef or chicken',
      'Rice',
      'Onion',
      'Garlic',
      'Tomatoes',
      'Ají amarillo (yellow chili pepper)',
      'Hard-boiled eggs',
      'Black olives',
      'Raisins',
      'Hard-boiled eggs',
      'Milk',
      'Butter',
      'Cheese',
      'Salt',
      'Pepper',
      'Cilantro (for garnish)',
    ],
  },
  {
    name: 'Alfajor',
    origin: 'Spain',
    imgUrl: 'assets/alfajor.png',
    ingredients: [
      'Unsalted butter, at room temperature',
      'Granulated sugar',
      'Large egg yolks',
      'Vanilla extract',
      'All-purpose flour',
      'Cornstarch',
      'Baking powder',
      'Pinch of salt',
      'Dulce de leche (traditional caramel filling)',
      'Powdered sugar (for dusting)',
      'Shredded coconut (optional)',
    ],
  },
  {
    name: 'Arroz Con Pollo',
    origin: 'Peru',
    imgUrl: 'assets/arroz_con_pollo.png',
    ingredients: [
      'Chicken pieces (such as thighs, drumsticks, or breast)',
      'Rice',
      'Chicken broth or water',
      'Onion',
      'Garlic',
      'Bell peppers (red, green, or yellow)',
      'Tomatoes',
      'Frozen peas',
      'Carrots',
      'Green olives',
      'Cilantro',
      'Saffron threads or ground turmeric (for color and flavor)',
      'Salt',
      'Black pepper',
      'Paprika',
      'Olive oil',
      'Lemon juice',
    ],
  },
  {
    name: 'Causa Rellena',
    origin: 'Peru',
    imgUrl: 'assets/causa_rellena.png',
    ingredients: [
      'Yellow potatoes (papas amarillas)',
      'Lime juice',
      'Yellow chili pepper paste (aji amarillo paste)',
      'Vegetable oil',
      'Salt',
      'Cooked and shredded chicken, tuna, or other filling of choice',
      'Mayonnaise',
      'Avocado',
      'Lime juice',
      'Red onion, finely chopped',
      'Hard-boiled eggs, sliced',
      'Black olives',
      'Lettuce leaves, for serving',
      'Tomato slices, for serving',
      'Fresh cilantro or parsley, for garnish',
    ],
  },
  {
    name: 'Gang Keow Wan Gai',
    origin: 'Thai',
    imgUrl: 'assets/gang_keow_wan_gai.png',
    ingredients: [
      'Chicken breast or thigh, thinly sliced',
      'Green curry paste',
      'Coconut milk',
      'Fish sauce',
      'Palm sugar or brown sugar',
      'Thai eggplant, cut into wedges',
      'Bell peppers, sliced',
      'Bamboo shoots, sliced',
      'Thai basil leaves',
      'Kaffir lime leaves',
      'Thai red chili peppers, thinly sliced (optional, for extra heat)',
      'Cooked jasmine rice, for serving',
    ],
  },
  {
    name: 'Kao Pad',
    origin: 'Thai',
    imgUrl: 'assets/kao_pad.png',
    ingredients: [
      'Cooked jasmine rice, preferably day-old',
      'Cooked chicken, shrimp, or tofu (or a combination)',
      'Vegetable oil',
      'Garlic, minced',
      'Eggs, lightly beaten',
      'Onion, diced',
      'Carrot, diced',
      'Frozen peas',
      'Fish sauce',
      'Soy sauce',
      'Oyster sauce',
      'Sugar',
      'Green onions, chopped',
      'Fresh cilantro, chopped',
      'Lime wedges, for serving',
    ],
  },
]
