export const FOOD_ITEMS = [
  {
    name: 'Pad Thai',
    origin: 'Thailand',
    imgUrl: 'assets/pad_thai.png',
    ingredients: [
      'rice noodle',
      'eggs',
      'bean sprouts',
      'scallions',
      'garlic',
      'shallots',
      'tamarind paste',
      'fish sauce',
      'palm sugar',
      'lime',
      'peanuts',
      'chili flakes',
      'cilantro',
    ],
  },
  {
    name: 'Lomo Saltado',
    origin: 'Peru',
    imgUrl: 'assets/lomo_saltado.png',
    ingredients: [
      'beef',
      'rice',
      'onion',
      'tomatoes',
      'bell peppers',
      'garlic',
      'soy sauce',
      'vinegar',
      'cilantro',
      'aji amarillo paste',
    ],
  },
  {
    name: 'Aguadito',
    origin: 'Peru',
    imgUrl: 'assets/aguadito.png',
    ingredients: [
      'Chicken (whole or in pieces)',
      'Rice',
      'Cilantro',
      'Aji amarillo (yellow chili pepper)',
      'Onion',
      'Garlic',
      'Vegetables (such as peas, carrots, and corn)',
      'Vegetable or chicken broth',
      'Lime juice',
      'Salt',
      'Pepper',
    ],
  },
  {
    name: 'Aji De Gallina',
    origin: 'Peru',
    imgUrl: 'assets/aji_de_gallina.png',
    ingredients: [
      'Chicken breast',
      'Aji amarillo (yellow chili pepper)',
      'Bread slices (for thickening)',
      'Milk',
      'Vegetable oil',
      'Onion',
      'Garlic',
      'Ground walnuts or pecans',
      'Parmesan cheese',
      'Evaporated milk',
      'Salt',
      'Pepper',
      'Boiled eggs (optional, for garnish)',
      'Black olives (optional, for garnish)',
      'Rice or potatoes (served as a side)',
    ],
  },
  {
    name: 'Arroz Tapado',
    origin: 'Peru',
    imgUrl: 'assets/arroz_tapado.png',
    ingredients: [
      'Ground beef or chicken',
      'Rice',
      'Onion',
      'Garlic',
      'Tomatoes',
      'Ají amarillo (yellow chili pepper)',
      'Hard-boiled eggs',
      'Black olives',
      'Raisins',
      'Hard-boiled eggs',
      'Milk',
      'Butter',
      'Cheese',
      'Salt',
      'Pepper',
      'Cilantro (for garnish)',
    ],
  },
  {
    name: 'Alfajor',
    origin: 'Spain',
    imgUrl: 'assets/alfajor.png',
    ingredients: [
      'Unsalted butter, at room temperature',
      'Granulated sugar',
      'Large egg yolks',
      'Vanilla extract',
      'All-purpose flour',
      'Cornstarch',
      'Baking powder',
      'Pinch of salt',
      'Dulce de leche (traditional caramel filling)',
      'Powdered sugar (for dusting)',
      'Shredded coconut (optional)',
    ],
  },
  {
    name: 'Arroz Con Pollo',
    origin: 'Peru',
    imgUrl: 'assets/arroz_con_pollo.png',
    ingredients: [
      'Chicken pieces (such as thighs, drumsticks, or breast)',
      'Rice',
      'Chicken broth or water',
      'Onion',
      'Garlic',
      'Bell peppers (red, green, or yellow)',
      'Tomatoes',
      'Frozen peas',
      'Carrots',
      'Green olives',
      'Cilantro',
      'Saffron threads or ground turmeric (for color and flavor)',
      'Salt',
      'Black pepper',
      'Paprika',
      'Olive oil',
      'Lemon juice',
    ],
  },
  {
    name: 'Causa Rellena',
    origin: 'Peru',
    imgUrl: 'assets/causa_rellena.png',
    ingredients: [
      'Yellow potatoes (papas amarillas)',
      'Lime juice',
      'Yellow chili pepper paste (aji amarillo paste)',
      'Vegetable oil',
      'Salt',
      'Cooked and shredded chicken, tuna, or other filling of choice',
      'Mayonnaise',
      'Avocado',
      'Lime juice',
      'Red onion, finely chopped',
      'Hard-boiled eggs, sliced',
      'Black olives',
      'Lettuce leaves, for serving',
      'Tomato slices, for serving',
      'Fresh cilantro or parsley, for garnish',
    ],
  },
  {
    name: 'Gang Keow Wan Gai',
    origin: 'Thai',
    imgUrl: 'assets/gang_keow_wan_gai.png',
    ingredients: [
      'Chicken breast or thigh, thinly sliced',
      'Green curry paste',
      'Coconut milk',
      'Fish sauce',
      'Palm sugar or brown sugar',
      'Thai eggplant, cut into wedges',
      'Bell peppers, sliced',
      'Bamboo shoots, sliced',
      'Thai basil leaves',
      'Kaffir lime leaves',
      'Thai red chili peppers, thinly sliced (optional, for extra heat)',
      'Cooked jasmine rice, for serving',
    ],
  },
  {
    name: 'Kao Pad',
    origin: 'Thai',
    imgUrl: 'assets/kao_pad.png',
    ingredients: [
      'Cooked jasmine rice, preferably day-old',
      'Cooked chicken, shrimp, or tofu (or a combination)',
      'Vegetable oil',
      'Garlic, minced',
      'Eggs, lightly beaten',
      'Onion, diced',
      'Carrot, diced',
      'Frozen peas',
      'Fish sauce',
      'Soy sauce',
      'Oyster sauce',
      'Sugar',
      'Green onions, chopped',
      'Fresh cilantro, chopped',
      'Lime wedges, for serving',
    ],
  },
  {
    name: 'Cau Cau',
    origin: 'Peru',
    imgUrl: 'assets/cau_cau.png',
    ingredients: [
      'Beef tripe (panza de res) or chicken breast, diced',
      'Potatoes, peeled and diced',
      'Vegetable oil',
      'Onion, finely chopped',
      'Garlic, minced',
      'Aji amarillo paste (yellow chili pepper paste)',
      'Turmeric powder',
      'Cumin',
      'Chicken or beef broth',
      'Peas',
      'Carrots, diced (optional)',
      'Corn kernels (optional)',
      'Boiled eggs, sliced (optional)',
      'Black olives (optional)',
      'Hard-boiled eggs, sliced (for garnish)',
      'Fresh parsley or cilantro, chopped (for garnish)',
      'Lime wedges, for serving',
      'Salt and pepper, to taste',
    ],
  },
  {
    name: 'Chupe De Camarones',
    origin: 'Peru',
    imgUrl: 'assets/chupe_de_camarones.png',
    ingredients: [
      'Shrimp, peeled and deveined',
      'Fish or seafood stock',
      'Potatoes, diced',
      'Corn kernels (fresh or frozen)',
      'Carrots, diced',
      'Green peas',
      'Onion, finely chopped',
      'Garlic, minced',
      'Aji amarillo paste (yellow chili pepper paste)',
      'Milk or evaporated milk',
      'Eggs',
      'Fresh cheese (queso fresco), diced or crumbled',
      'Fresh cilantro or parsley, chopped',
      'Olive oil or vegetable oil',
      'Butter',
      'Salt and pepper, to taste',
      'Lime wedges, for serving',
    ],
  },
  {
    name: 'Larb Gai',
    origin: 'Thai',
    imgUrl: 'assets/larb_gai.png',
    ingredients: [
      'Ground chicken',
      'Shallots, thinly sliced',
      'Green onions, thinly sliced',
      'Fresh cilantro, chopped',
      'Fresh mint leaves, chopped',
      'Fresh lime juice',
      'Fish sauce',
      'Roasted ground rice powder',
      'Thai chili peppers, finely chopped (optional, for extra heat)',
      'Lettuce leaves, for serving',
      'Cucumber slices, for serving',
      'Sticky rice or steamed jasmine rice, for serving',
    ],
  },
  {
    name: 'Summer Roll',
    origin: 'Vietnam',
    imgUrl: 'assets/summer_roll.png',
    ingredients: [
      'Rice paper wrappers',
      'Rice vermicelli noodles, cooked and cooled',
      'Shrimp, cooked and peeled (or tofu for vegetarian option)',
      'Lettuce leaves (such as butter lettuce or romaine)',
      'Fresh herbs (such as mint, cilantro, and Thai basil)',
      'Cucumber, julienned',
      'Carrot, julienned',
      'Bean sprouts',
      'Optional additional vegetables: bell peppers, avocado, mango slices, etc.',
      'Optional additional protein: cooked chicken, pork, or beef slices',
      'Optional additional fillings: rice paper sheets, avocado, mango, etc.',
      'Hoisin sauce or peanut sauce, for dipping',
    ],
  },
  {
    name: 'Helado De Lucuma',
    origin: 'Peru',
    imgUrl: 'assets/helado_de_lucuma.png',
    ingredients: [
      'Lucuma pulp or Lucuma powder',
      'Milk or cream (or a combination of both)',
      'Sugar or sweetened condensed milk',
      'Egg yolks (optional, for added richness)',
      'Vanilla extract (optional, for flavor)',
      'Salt (a pinch, to enhance flavor)',
    ],
  },
  {
    name: 'Juane',
    origin: 'Peru',
    imgUrl: 'assets/juane.png',
    ingredients: [
      'Banana leaves (for wrapping)',
      'Rice',
      'Chicken (or other protein such as fish or pork), diced',
      'Boiled eggs',
      'Olives',
      'Raisins',
      'Cilantro',
      'Aji amarillo (yellow chili pepper), fresh or paste',
      'Cumin',
      'Garlic',
      'Onion',
      'Salt',
      'Pepper',
      'Hard-boiled eggs (optional, for garnish)',
      'Sauce (such as salsa criolla or aji sauce, for serving)',
    ],
  },
  {
    name: 'Banh Mi',
    origin: 'Vietnam',
    imgUrl: 'assets/banh_mi.png',
    ingredients: [
      'Baguette or Vietnamese-style bread',
      'Pâté (usually pork liver pâté)',
      'Mayonnaise or aioli',
      'Pickled daikon radish',
      'Pickled carrots',
      'Cucumber, thinly sliced',
      'Fresh cilantro leaves',
      'Fresh jalapeño or Thai bird chili, thinly sliced',
      'Soy sauce or Maggi seasoning',
      'Sliced pork, chicken, beef, or tofu (or a combination)',
      'Optional additional ingredients: Vietnamese sausage (cha lua), head cheese (gio lua), fried egg, grilled pork belly (thit nuong), etc.',
    ],
  },
  {
    name: 'Pho',
    origin: 'Vietnam',
    imgUrl: 'assets/pho.png',
    ingredients: [
      'Beef bones (for making broth)',
      'Water',
      'Onion',
      'Ginger',
      'Star anise',
      'Cinnamon stick',
      'Cloves',
      'Coriander seeds',
      'Cardamom pods',
      'Rock sugar (or granulated sugar)',
      'Fish sauce',
      'Salt',
      'Rice noodles',
      'Thinly sliced beef (such as sirloin or eye of round)',
      'Bean sprouts',
      'Thai basil leaves',
      'Cilantro',
      'Lime wedges',
      'Sliced chili peppers',
      'Hoisin sauce',
      'Sriracha or chili garlic sauce',
    ],
  },
  {
    name: 'Beef Chow Fun',
    origin: 'China',
    imgUrl: 'assets/beef_chow_fun.png',
    ingredients: [
      'Flat rice noodles (fresh or dried)',
      'Beef (flank steak or sirloin), thinly sliced',
      'Green onions, cut into 2-inch pieces',
      'Bean sprouts',
      'Chinese broccoli (gai lan) or regular broccoli, cut into florets',
      'Garlic, minced',
      'Ginger, minced',
      'Light soy sauce',
      'Dark soy sauce',
      'Oyster sauce',
      'Shaoxing wine (or dry sherry)',
      'Cornstarch',
      'Vegetable oil',
      'Salt',
      'White pepper',
    ],
  },
  {
    name: 'Mu Shu Pork',
    origin: 'China',
    imgUrl: 'assets/mu_shu_pork.png',
    ingredients: [
      'Pork tenderloin or pork shoulder, thinly sliced',
      'Wood ear mushrooms, rehydrated and thinly sliced',
      'Cabbage, thinly shredded',
      'Carrots, julienned',
      'Green onions, thinly sliced',
      'Garlic, minced',
      'Ginger, minced',
      'Eggs, lightly beaten',
      'Hoisin sauce',
      'Soy sauce',
      'Sesame oil',
      'Rice vinegar',
      'Cornstarch',
      'Vegetable oil',
      'Mandarin pancakes or flour tortillas (for serving)',
    ],
  },
  {
    name: 'Soup Dumpling',
    origin: 'China',
    imgUrl: 'assets/soup_dumpling.png',
    ingredients: [
      'Ground pork (or other meat such as chicken or shrimp)',
      'Ginger, minced',
      'Green onions, finely chopped',
      'Soy sauce',
      'Sesame oil',
      'Rice wine or Shaoxing wine',
      'Chicken broth, chilled and solidified (for the soup filling)',
      'Gelatin or agar-agar (optional, for solidifying the soup)',
      'Dumpling wrappers',
      'Water (for sealing the dumplings)',
      'Black vinegar (for dipping)',
      'Ginger, thinly sliced (for dipping)',
    ],
  },
]
